repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
        exclude: ^notebooks/
    -   id: end-of-file-fixer
        exclude: ^notebooks/
    -   id: trailing-whitespace
        exclude: ^notebooks/
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: ^notebooks/
        args:
        - --line-length=120
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        exclude: ^notebooks/
        args:
        - --convention=google
        - --add-ignore=D107
-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    -   id: darglint
        exclude: ^notebooks/
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        exclude: ^notebooks/
        args: ["--profile", "black"]
-   repo: local
    hooks:
    -   id: pylint
        exclude: ^notebooks/
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
            [
              "-rn", # Only display messages
            ]
