repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
    -   id: bandit
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        args:
        - --convention=google
        - --add-ignore=D107
-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    -   id: darglint
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]
