# -*- coding: utf-8 -*-
"""wildlifeai-cli-demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10EfcEG9XDC64soj3GSXE6pX8rvBGKFrr
"""

#upgrade gspread since default version does not support export of worksheet
!pip install --upgrade gspread --quiet

"""# Demo for creating edge impulse dataset

This notebook will show you how to install and use the wai_data_tools package for creating your own dataset to use in Edge Impulse.

To run this you need to do two preparatory steps:
1. Mount your Drive to Colab and make sure that you have added the data as a shortcut to your drive if someone has shared the raw data with you.
2. Authenticate yourself and give colab access to your google sheets. This is to export the ww_labels sheet to .xlsx format

Please make note of the paths to the raw data root directory.
"""

# Run to mount drive to the Colab session
from google.colab import drive

drive.mount('/content/drive')

import gspread
from google.auth import default

# Run to export the ww_labels sheet to .xlsx format
from google.colab import auth

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

sheet = gc.open_by_url("https://docs.google.com/spreadsheets/d/1Os-cFB7ZJQK-M4BMyfPTWiVE_14H8ddOZyWMtc2isPQ")
export_bytes = sheet.export(format="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
PATH_TO_EXCEL = "/content/ww_labels.xlsx"
with open(PATH_TO_EXCEL, 'wb') as export_file:
  export_file.write(export_bytes)

# Set this to the path to the root folder containing the raw data. Look in the "FILER" Tab to the right if unsure.
PATH_TO_RAW_DATA = "/content/drive/MyDrive/WW_taranaki_labelled"
# Set this to your desired output folder.
PATH_TO_STORE_DATA = "/content/test"

"""## Setup"""

# Commented out IPython magic to ensure Python compatibility.
!pip install --upgrade gspread
!git clone -b fixed-opencv-import https://github.com/wildlifeai/wai_data_tools.git
# %cd wai_data_tools
!pip install pipenv
!pipenv lock
!pipenv install
!pipenv run pip install .
!mkdir {PATH_TO_STORE_DATA}

!pipenv run wildlifeai-cli create-ei-dataset --excel_filepath={PATH_TO_EXCEL} --src_video_dir={PATH_TO_RAW_DATA} --dst_root_dir={PATH_TO_STORE_DATA}

"""If successful, your output folder should now have two subfolders called **train** and **test**. The contents of these can be uploaded to Edge Impulse and labels will be automatically inferred if you have selected the option **"Infer from filename"**."""
