labels:
  - name: rat
    is_target: True
    sampling_frequency: 1
  - name: weta
    is_target: True
    sampling_frequency: 1
  - name: millipede
    is_target: False
    sampling_frequency: 2
preprocessing:
  transformations:
      img_size:
        - 48
        - 48
logging:
  logging_dir: default
  logging_config_file: default
